apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ccla6qyzo-python 
  janus-idp.io/tekton: ccla6qyzo-python
  backstage.io/kubernetes-id: ccla6qyzo-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ccla6qyzo-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  