apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ccla6qyzo-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ccla6qyzo-python 
  name: ccla6qyzo-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ccla6qyzo-python 
